### ISSUE TITLE
Logout is not working

### ISSUE THREAD

**Issue by prathviraj080** [kahmali/meteor-restivus#104]
Request:
```bash
$ curl  http://localhost:3000/api/login/ -d "password=XXXXX&user=XXX@XXX.com"
```

Response:
```json
{
  "status": "success",
  "data": {
    "authToken": "-yOSL9w0-4s6vXpVXeypEyyTVNuKVyh3HyyqJ-hbo4d",
    "userId": "swwpNfbQATp7St9tH"
  }
}
```

Request:
```bash
$ curl http://localhost:3000/api/logout -H "X-Auth-Token: -yOSL9w0-4s6vXpVXeypEyyTVNuKVyh3HyyqJ-hbo4d" -H "X-User-Id: swwpNfbQATp7St9tH"
```

Response:
```json
{
  "status": "error",
  "message": "You must be logged in to do this."
}
```

**Comment by kahmali** [comment]
Thanks for reporting the issue. What version are you using? I just want to make sure I'm testing against the same version you're on.

**Comment by prathviraj080** [comment]
Its restivus@0.7.1

**Comment by kahmali** [comment]
Could you provide me with more detailed reproduction steps, or maybe a test repository demonstrating the issue? I'm running the commands you provided, in v0.7.1, and I'm able to log a user out successfully. The response is:

```json
{ "status":"success", "data": { "message":"You've been logged out!" } }
```

There must be something else going on with your configuration. I'm sure we can figure it out.

**Comment by prathviraj080** [comment]
Sorry, my bad. Problem was with my configuration. Thank you for your time
