### ISSUE TITLE
Restivus is not defined

### ISSUE THREAD

**Issue by Jayuda** [kahmali/meteor-restivus#107]
Hello Mr,
i use restivus on my app, its work well. but on console show : Uncaught ReferenceError: Restivus is not defined.
Whats should i do ?
Thanks

**Comment by kahmali** [comment]
Hi @Jayuda! That is the intended behavior. Restivus is a [server-only package](https://github.com/kahmali/meteor-restivus#writing-a-restivus-api). Just move all your Restivus code onto the server and that will get rid of the error. Feel free to reopen this issue if that doesn't solve the problem.

**Comment by Jayuda** [comment]
Yes, its work now 
Thanks Mr. @kahmali

**Comment by mspkom** [comment]
I added 'meteor add nimble:restivus' to my meteor project and did a simple 'main.js' inside of my server folder. 

var Api = new Restivus({
		useDefaultAuth: true,
		prettyJson: true
	});
console.log(Api);

The output in the console is: ReferenceError: Restivus is not defined

What do I do wrong?

**Comment by kahmali** [comment]
@mspkom Please provide a sample repo that reproduces this bug. I can assure you that when used as instructed in the documentation, `Restivus` will be available on the server.

**Comment by shemeermali** [comment]
@mspkom Could you fix the issue?
