### ISSUE TITLE
`new Restivus` failing

### ISSUE THREAD

**Issue by AlexFrazer** [kahmali/meteor-restivus#109]
I am trying to create a versioned api.

```
var ApiV1 = new Restivus({
  version: 'v1'
});
```

this failed, with the error "object is not a function". I then tried to use it on shell.

```
> var ApiV1 = new Restivus()
TypeError: object is not a function
    at repl:1:13
    at <path>/meteor/.meteor/local/build/programs/server/shell-server.js:243:23
```

**Comment by kahmali** [comment]
Are you doing this from the client? Restivus is a server-only package. If that's not the issue, could you please provide more detailed reproduction steps, or a sample repository demonstrating the issue? The more information, the better. Thanks!

**Comment by kahmali** [comment]
Also, which version of Restivus are you using?

**Comment by AlexFrazer** [comment]
Ah, I've found the problem... can't update while meteor is running and running the update in a different tab doesn't take effect.
