### ISSUE TITLE
Announcement: Project maintainer on vacation

### ISSUE THREAD

**Issue by kahmali** [kahmali/meteor-restivus#110]
Hi everyone!

Just a heads up that I will be traveling on vacation for the next two weeks. I'll still pop in from time to time and try to address any new issues, but it may be days, or even a week, before I'm able to respond. Development will certainly be slow, if at all existent, during this period. I will resume my regular activity on July 25th. Now, it's time for me to get some REST and relaxation. See what I did there? ;) 

Take care!

**Comment by sroze** [comment]
Should be closed now ? :)
