### ISSUE TITLE
connect.multipart() and connect.limit() will be removed in connect 3.0

### ISSUE THREAD

**Issue by nooitaf** [kahmali/meteor-restivus#118]
I'm getting those errors/warnings on startup with `v0.8.1`:
```text
=> Meteor server restarted
(STDERR) connect.multipart() will be removed in connect 3.0
(STDERR) visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
(STDERR) connect.limit() will be removed in connect 3.0
```

**Comment by nooitaf** [comment]
Whoops, unrelated to restivus. 
Its a `json-routes` issue https://github.com/stubailo/meteor-rest/issues/18

**Comment by kahmali** [comment]
Thanks for submitting that PR for `simple:json-routes`. I've updated the dependency in Restivus to the latest version, so the deprecation warnings are gone. Restivus v0.8.2 is now published with these changes. Great work!

**Comment by nooitaf** [comment]
\o/
