### ISSUE TITLE
userId Environment Contamination

### ISSUE THREAD

**Issue by mariorodriguespt** [kahmali/meteor-restivus#119]
I recently discovered that if you use collection-hooks hooks that rely on the `userId`, for some reason, the userId parameter is randomly changed.

My scenario: I'm using a browser plugin to insert to a collection, I've access to `this.userId` in the endpoint function but If have 1 user that is logged in using the REST API my hooks get contaminated. The obvious bug was adding a document with `ownerUsername`field as user A but user B appears instead, I was also able to login with user C in the REST API and got the user C instead of A. The real problem appears when I'm inserting documents without using the REST API but I've at least 1 user logged in.

I don't know which package is "guilty" yet, I know collection-hooks has an environment bug github issue open but it's due to concurrency, however my scenario doesn't requires 2 user inserting at the same time.

There is a change simple-schema is also affect if you `autoValue` and potentially other packages.

I'll post a git repo soon if I'm able to replicate the problem.

**Comment by kahmali** [comment]
The sample repo would help a bunch. I'll take a look when you post that.

**Comment by mariorodriguespt** [comment]
The problem was not related to this package.

I decided to drop this package in favor of a DDP connection. However, it would be nice to create a fibers environment with a userId on each ajax call because, in my case, I have collection hooks that heavily depend on it.

**Comment by aramk** [comment]
I'm having a similar issue where collection hooks have an undefined userId. Collection hooks has a CollectionHooks.getUserId() so having a global method which returns the userId (if any) from within the REST API request would be handy. Otherwise, the request would ensure that Meteor.userId() returns the correct user during the request.
