### ISSUE TITLE
Example of how to call a 3rd party API with meteor in restivus

### ISSUE THREAD

**Issue by reduxdj** [kahmali/meteor-restivus#120]
Api.addRoute 'products', authRequired: false,
      get: ->
        products = Meteor.http.get 'https://api.instagram.com/v1/tags/shoes/media/recent?access_token=XXX', (error, result) ->
          return products

    status: 'success', data: products

returns before the async request

**Comment by kahmali** [comment]
Just remove the callback in your call to `Http.get()` and it'll run synchronously. Did mdg move that into the`Meteor` namespace? For more on running asynchronous code from a Restivus endpoint, check out #11. 

If that doesn't solve your problem, feel free to reopen this issue.
