### ISSUE TITLE
How to modify PUT to simulate PATCH

### ISSUE THREAD

**Issue by dheerajbhaskar** [kahmali/meteor-restivus#131]
Hi guys,

## Goal
We need to update documents in our collections via REST. Until JSON PATCH comes out, how can we  modify PUT so that it doesn't replace the whole document, but updates the given document with new key:value pairs sent via REST. The route shouldn't update keys not mentioned in PUT.

If you know a better way to update the document which has been already implemented in restivus, please let me know.

PS: I know restivus tries to stick to standards of REST API and PUT is only supposed to replace, but we need to make do with a workaround until JSON PATCH support comes out.

**Comment by kahmali** [comment]
Wow. I am so sorry that this went unanswered for so long! At some point in the last few weeks I typed up a response to this and must have gotten sidetracked and never sent it. I'm so sorry about that! 

I also apologize for not making it possible to simply provide a PATCH method on collection routes. I completely understand the need for partially updating a resource. I thought I was going to implement the PATCH support a lot sooner, or I would have made more of an effort to allow a custom PATCH method to be defined on collections in the interim. As soon as I have some time to update Restivus I will be sure to add support for this. 

In the meantime, you can provide a [custom `put` endpoint](https://github.com/kahmali/meteor-restivus#action) on all your collection routes. I would write the function where it was accessible to all collection routes, and reuse it throughout your API. Here's an example (it's in coffeescript to save me time and energy. If you need to convert it to JS go here: http://js2.coffee/):

```coffeescript
Api = new Restivus()

# Do your partial patch (need to pass in collection since Restivus is evil and 
# doesn't do it for you in collection routes
patch = (collection) ->
  return ->
    # I recommend setting this up as an atomic transaction and validating data
    # (I don't do it here)
    _.each @bodyParams, (value, key) ->
      updatedField = {}
      updatedField[key] = value
      collection.update @urlParams.id, updatedField
    # Need to check for success/failure, instead of just assuming success here
    entity = collection.findOne @urlParams.id
    {status: 'success', data: entity}

Items = new Mongo.Collection 'Items'

Api.addCollection Items,
  endpoints:
    put: 
      action: patch(Items)

Widgets = new Mongo.Collection 'Widgets'

Api.addCollection Widgets,
  endpoints:
    put: 
      action: patch(Widgets)
```

I just freehanded that code in a bit of a rush. If you see me doing anything glaringly stupid there just point it out and I'll fix it. 

Let me know if that helps. Again, I can't apologize enough for the insanely delayed response. Sorry about that!

**Comment by dheerajbhaskar** [comment]
Thanks for getting back kahmali and for the brilliant work so far.
We made our own custom put implementation.

Although, I'm not very familiar with CoffeScript, I see that there's not $set operator implementation, is that on purpose?

I shall go ahead and close this issue, though we can continue to discuss this.
