### ISSUE TITLE
Overwriting standard POST endpoint doesn't work

### ISSUE THREAD

**Issue by a4xrbj1** [kahmali/meteor-restivus#133]
I want to overwrite the standard POST endpoint as part of a collection (via addCollection). This is my source code:

```js
// Global API configuration
    var Api = new Restivus({
        prettyJson: true
    });

Api.addCollection(Kits, {
        authRequired: false,
        excludedEndpoints: ['getAll', 'deleteAll', 'delete'],
        endpoints: {
            post: function () {
                var name = this.bodyParams.name;
                console.log ("Entity: " + JSON.stringify(name));
            }
        }
    });
```
I can't figure out why restivus (or meteor) isn't using the code that I entered under this custom endpoint and is instead using the default built-in behavior of just INSERTing it into the collection?

I want to avoid having duplicate entries (over fields other than the _id), hence I want to first check with a findOne and only INSERT when I can't find a record.

But the main problem is that for whatever reason I can't figure out why it's not executing my code

**Comment by a4xrbj1** [comment]
I'd like to further clarify my issue. When I use API.addCollection I do expect that I can alter the standard/default behavior of adding a document to the collection by using the POST command. I'd like to alter the code to check first for duplicates and reject them (I know this can be done via compound index in MongoDB as well - http://docs.mongodb.org/master/core/index-compound/) but the point is that there are cases where we want to run some code and hence want to overwrite the default behavior.

Yes, as someone else pointed out on Slack I could write my own route with Api.addRoute but that would mean I'm adding a new Endpoint.

So if anyone wants to keep the standard behavior for collection endpoints via Api.addCollection and code changes to it MUST be done via a different, custom endpoint then please state so explicitly in the documentation and you can close this issue.

Thank you!

**Comment by kahmali** [comment]
You know, it's been a while since I've used Restivus, and I don't have time to dig through the source right now. So, trusting my documentation, there's nothing that says you can use the shorthand way of just passing a function to a collection route. Try nesting that function under the [`post.action` property](https://github.com/kahmali/meteor-restivus#endpoint-configuration): 
```js
// Global API configuration
    var Api = new Restivus({
        prettyJson: true
    });

Api.addCollection(Kits, {
        authRequired: false,
        excludedEndpoints: ['getAll', 'deleteAll', 'delete'],
        endpoints: {
            post: 
              action: function () {
                  var name = this.bodyParams.name;
                  console.log ("Entity: " + JSON.stringify(name));
            }
        }
    });
```
If that doesn't work, then we may have a bug (although it's been pretty thoroughly tested, so i doubt that's the case). If you'd like to open a new issue with a request to allow the function to be passed directly, please do so (in fact, I may just hijack this thread if you don't open the new issue). Unfortunately, I'm a few weeks behind on a higher priority project, so realistically, it could be weeks before I get around to that. Sorry! Of course, I would gladly accept a PR for it.

**Comment by a4xrbj1** [comment]
Thanks @kahmali for your response. Your code change didn't run, I changed it to the following code (I hope I didn't make it wrong but at least there was no error anymore):

Api.addCollection(Kits, {
        authRequired: false,
        excludedEndpoints: ['getAll', 'deleteAll', 'delete'],
        endpoints: {
        post: {authRequired: false},
            action: function () {
                var name = this.bodyParams.name;
                console.log ("Entity: " + JSON.stringify(name));
            }
        }
    });

However, this action is never executed. It's still the same problem, this default function inserts data without any chance to check. Apart from having unwanted data in the collection it might present also a security problem (I'm not an expert on this).

In the meantime I have found a way around it by defining a customer router via Api.addRoute and disabling the default POST on this collection (but I still believe that there should be a possibility to inject code to eg check what is inserted before it happens automatically).

Unfortunately I can't help further as I have a MVP launch date in 3 weeks, so the workaround is fine for me now as it doesn't hold me up anymore. Maybe others can jump in.

**Comment by kahmali** [comment]
Sorry, I use coffeescript primarily, and sometimes I forget that I'm answering questions in JS. I was just missing some pesky curly braces. The code that you changed it to would not run. `authRequired` and `action` are sibling properties, as I think is clear in the documentation I linked to above. So it should be:
```js
    Api.addCollection(Kits, {
        authRequired: false,
        excludedEndpoints: ['getAll', 'deleteAll', 'delete'],
        endpoints: {
            post: {
                authRequired: false,
                action: function () {
                    var name = this.bodyParams.name;
                    console.log ("Entity: " + JSON.stringify(name));
                }
            }
        }
    });
```
Your code above omitted the action, so I wouldn't expect it to have run. As far as injecting code into endpoints, that's a job for middleware. I suggest you read up on the topic, as it solves many problems and can make for a much cleaner API. I hope to provide better support for middleware in Restivus (I discuss it a bit in response to another issue [here](https://github.com/kahmali/meteor-restivus/issues/129#issuecomment-133120800)).

**Comment by kahmali** [comment]
Did my suggestion work, or did you just stick with the custom route?

**Comment by a4xrbj1** [comment]
It works when a value other than null or undefined is returned from the endpoint. That was missing in the above sample, other than that it works fine now. Thank you @kahmali
