### ISSUE TITLE
Upload base64 encoded image with restivus using post and download it using get

### ISSUE THREAD

**Issue by isdzulqor** [kahmali/meteor-restivus#152]
Hey @kahmali ,
Thank you for your library, it's help me so much. 
Could you explain to me how to upload base64 encoded image with restivus using post and download it using get? would you like to give some example code,, 
Thank you :)

**Comment by luixal** [comment]
Totally +1000

**Comment by gleslie2008** [comment]
Just convert your image to base64 and store it as a string in a Mongo object, ensuring you don't surpass [MongoDB's object size limits](https://docs.mongodb.org/v3.0/reference/limits/).  This is as simple as passing a string through a GET and POST request.

This is more of a question in scope of whatever you are developing your client in.

**Comment by kahmali** [comment]
What @gleslie2008 suggested should definitely work. Base64 is just a string value. It's file uploads that are tricky. I'm going to go ahead and close this, but feel free to reopen it if you're still having issues with it after trying that suggestion. Sorry it took me so long to respond. Thank you so much for answering this @gleslie2008, and thanks for the kind words @isdzulqor!
