### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by cerupcat** [kahmali/meteor-restivus#176]
I've added Restivus to a package I've made. When I call ```new Restivus()``` it crashes with ```TypeError: undefined is not a function```

Any ideas what the issue could be? I'm running Meteor version 1.2

**Comment by kahmali** [comment]
Are you calling that on the server? Restivus is [only available on the server](https://github.com/kahmali/meteor-restivus#writing-a-restivus-api). You should get that error on the client.

**Comment by cerupcat** [comment]
@kahmali no, this is on the server. It's wrapped in a ```if (Meteor.isServer) {``` and in the package the code is only included on the server as well.

**Comment by kahmali** [comment]
What version of Restivus are you using?

**Comment by kahmali** [comment]
And no, there's no hidden dependency that would cause Restivus to be completely unavailable on the server.

**Comment by cerupcat** [comment]
Thanks, from what I can tell if we had Restivus to our main app, then things work. When we create a package with Restivus for some reason it's not working. We tried to create a sample project using Restivus in a package and it worked. So, there's likely some conflict in Restivus (or its dependencies) with our own app. We'll have to go through all the code and dependencies to see what might be keeping it from working.

**Comment by kahmali** [comment]
What version of Restivus are you using in the package? Check the .versions file in the app when you load it as a package. Are you specifying the version as 0.8.4? That happens to me often with meteor packages in my apps. It defaults to a very low version if you don't specify, as there may be some perceived version conflict in your app.

**Comment by cerupcat** [comment]
Thanks, that fixed it! I wasn't setting the version number and it defaults to a really old version. Thanks again! Looking forward to using this! :)

**Comment by kahmali** [comment]
Awesome! That gets me all the time. Thanks for reporting the issue and following up. I'm sure you won't be the last to bump into that one.
