### ISSUE TITLE
Adding OPTIONS endpoint for login/logout

### ISSUE THREAD

**Issue by m52go** [kahmali/meteor-restivus#178]
Is there any way to do this?

I tried, among other things:

```
    Api.addRoute('login', { authRequired: false }, {
        options: {
            action: function() {
                return "{ Allow: POST }";
            }
        }
    });
```

Didn't work.

I'm having CORS issues, and adding that OPTIONS endpoint solved the issue for my other POST routes, but I can't figure out how to add it for the authentication endpoints.

Without this setting, no one can log in to my app!!

**Comment by m52go** [comment]
Nevermind, I missed the `defaultOptionsEndpoint` option. Sorry!

**Comment by kahmali** [comment]
Nothing to be sorry about. Glad you figured it out! Thanks for following up with your solution.
