### ISSUE TITLE
Maximum Request Length Exceeded

### ISSUE THREAD

**Issue by meghadev** [kahmali/meteor-restivus#179]
We are using the nimble:restivus package from atmosphere for our meteor application. However, we I placed a POST request with a huge amount of data, I got the response as "Maximum Request Length Exceeded".

How can I configure the same?

**Comment by ramzauchenna** [comment]
Its already a known issue [](https://github.com/kahmali/meteor-restivus/issues/78)

**Comment by meghadev** [comment]
Our product will soon be going into production and we urgently need a fix for the same. Is there any workaround??

**Comment by kahmali** [comment]
Please see the discussion [here](https://github.com/stubailo/meteor-rest/issues/75). I've already filed an issue on the `simple:json-routes` repo with a (_very_ simple) suggested fix, and another developer has a fork available in atmosphere with the fix until they can submit a PR. I'll keep this issue open until the PR is merged and I update the dependency.

**Comment by kahmali** [comment]
The request size limit has been increased to 50mb in v0.8.6.
