### ISSUE TITLE
CORS issue: Method DELETE is not allowed by Access-Control-Allow-Methods in preflight response.

### ISSUE THREAD

**Issue by RenMan** [kahmali/meteor-restivus#187]
I've hosted a very simple Meteor app on Modulus, using Restivus to provide a RESTful API for a front end which I'm hosting on my personal site.  The app is working properly when I test the various endpoints with Postman, but when trying to DELETE a document (which requires a preflight check since its cross-domain), I get the following error in the console: 

XMLHttpRequest cannot load http://hostname.here/api/groups/RCGWEKW2Eq4toTggQ. Method DELETE is not allowed by Access-Control-Allow-Methods in preflight response.

Initially, my Restivus config was very simple:
`        Api = new Restivus({
            useDefaultAuth: false,
            prettyJson: true,
        });`

and then I changed it to try to resolve this issue:
`        Api = new Restivus({
            enableCors: true,
            useDefaultAuth: false,
            prettyJson: true,
            defaultHeaders: {
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept',
                'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',
                'Content-Type': 'application/json'
            }
        });`

But no luck.

The front end is a vanilla backbone app (which uses jQuery ajax() to make its requests). 
Here's the request and response as captured by Charles Proxy:

REQUEST

```
OPTIONS /api/groups/RCGWEKW2Eq4toTggQ HTTP/1.1
Host: <host>
Access-Control-Request-Method: DELETE
Origin: http://craftedplaces.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
Access-Control-Request-Headers: accept
Accept: */*
Referer: <referrer>
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,es;q=0.6
```

RESPONSE

```
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Origin: *
Connection: keep-alive
Date: Fri, 26 Feb 2016 06:42:17 GMT
Vary: Accept-Encoding
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

I'm a complete noob when it comes to serving or consuming a RESTful API, so it's probably something very simple, but I can't find my solution anywhere.  I've noticed that the server's response does not contain an Access-Control-Allow-Methods header, but I don't know why.

**Comment by kahmali** [comment]
This is a known issue in Restivus. Check #125 for some potential solutions. I believe that you may be able to add the CORS headers by overriding the default OPTIONS endpoint. Check out [this answer](https://github.com/kahmali/meteor-restivus/issues/125#issuecomment-173989996). I'm going to close this as a duplicate, since it's a general issue with CORS and not just the DELETE method. If I'm wrong feel free to reopen it and discuss. 

If that suggestion works for you it would be awesome if you could post that in the thread I linked above. Just so more folks know that the suggested fix works. Then I can work on getting it built into Restivus. If the fix doesn't work, then you should continue to discuss it in that thread.

**Comment by RenMan** [comment]
Thanks, kahmali, for answering so quickly!  I figured it was a duplicate question, but reading through other posts, I couldn't figure out how to fix my problem.  I had read through that issue, but missed the comment about defaultOptionsEndpoint.

**Comment by kahmali** [comment]
No problem! Hope that fixes it for you.

**Comment by RenMan** [comment]
I'm not able to reopen the issue, but I'm afraid the server is responding now to my OPTIONS request with a 500 error:

`XMLHttpRequest cannot load http://hostname.here/api/groups/DpttNwXozmJ5uM3Ad. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://craftedplaces.com' is therefore not allowed access. The response had HTTP status code 500.`

REQUEST

```
OPTIONS /api/groups/DpttNwXozmJ5uM3Ad HTTP/1.1
Host: <host>
Access-Control-Request-Method: DELETE
Origin: http://craftedplaces.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
Access-Control-Request-Headers: accept
Accept: */*
Referer: <referrer>
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,es;q=0.6
```

RESPONSE

```
HTTP/1.1 500 Internal Server Error
Date: Fri, 26 Feb 2016 16:26:20 GMT
Content-Length: 47
Content-Type: text/plain; charset=utf-8

Unable to connect to any application instances.
```

That response confuses me because the server is up and running and responds to a request to GET the collection without issue.

Here's my code for the Restivus config:
 ```
Api = new Restivus({
            enableCors: true,
            useDefaultAuth: false,
            prettyJson: true,
            defaultOptionsEndpoint: function() {
                this.response.writeHead(201, {
                    'Access-Control-Allow-Origin': '*',
                    'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Z-Key',
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
                });
            }
        });
```

The only thing I changed from the answer in the other thread was removing the final comma after 
`'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'`

**Comment by RenMan** [comment]
I'm about to try 
```
Api = new Restivus({
            enableCors: true,
            useDefaultAuth: false,
            prettyJson: true,
            defaultOptionsEndpoint: {
                action: function() {
                    this.response.writeHead(201, {
                        'Access-Control-Allow-Origin': '*',
                        'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Z-Key',
                        'Content-Type': 'application/json',
                        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
                    });
                }
            }
        });
```

**Comment by RenMan** [comment]
That reconfiguration didn't have any effect.

**Comment by RenMan** [comment]
OK, I've **resolved** my issue by using 
```
        Api = new Restivus({
            enableCors: true,
            useDefaultAuth: false,
            prettyJson: true,
            defaultOptionsEndpoint: {
                action: function() {
                    this.response.writeHead(201, {
                        'Access-Control-Allow-Origin': '*',
                        'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Z-Key',
                        'Content-Type': 'application/json',
                        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
                    });
                    this.done();
                    return {
                        status: "success",
                        "data": {
                            "message": "We love OPTIONS"
                        }
                    };
                }
            }
        });
```

I'll post a comment on the [other thread](https://github.com/kahmali/meteor-restivus/issues/125#issuecomment-173989996), since its likely to be the landing point for people researching this issue.

**Comment by hassansardarbangash** [comment]
@RenMan I tried you solution but it still not working for me
