### ISSUE TITLE
How to log user out?

### ISSUE THREAD

**Issue by harinsa** [kahmali/meteor-restivus#19]
Can you give an example request for how to log the user out like the one you gave with the login?

**Comment by harinsa** [comment]
OK, I was able to logout using the command below. But I think it would be nice if this is included in the readme from that start.

`curl -H "X-Auth-Token: Qcn9l4_7newVg0GTqJE4jJ2bJe47FFPEhzP4XIVg2l2" -H "X-User-Id: aYQQKBf4SHdPZyhvh" -G http://localhost:3000/api/logout/`

**Comment by kahmali** [comment]
Sorry about that omission. Glad you figured it out. I updated the [Authenticating](https://github.com/kahmali/meteor-restivus#authenticating) section of the docs to include this information. Let me know if you think I missed anything, or if you run into any other issues. Thanks for reporting this!

**Comment by harinsa** [comment]
Glad that I was of some help!
