### ISSUE TITLE
authRequired: true returning "You must be logged in to do this." when valid X-Auth-Token and X-User-Id headers submitted

### ISSUE THREAD

**Issue by leanwebtools** [kahmali/meteor-restivus#209]
New to Meteor, getting used to things, like the look of **restivus**. 

I've set up a simple test to try out authenticated access but I seem to run into an issue when adding **authRequired: true** to **routeOptions** or an **endpoint**.

Here's the code (basically your example added to a new meteor app, with the addition of an Organization collection):

```js
    import { Meteor } from 'meteor/meteor';
    
    Organizations = new Mongo.Collection('organizations');
    
    Meteor.startup(() => {
    
        if (Meteor.isServer) {
    
            var Api = new Restivus({
                apiPath: 'api/',
                version: 'v1',
                auth: {
                    token: 'auth.apiKey',
                    user: function () {
                        return {
                            userId: this.request.headers['user-id'],
                            token: this.request.headers['login-token']
                        };
                    }
                },
                defaultHeaders: {
                    'Content-Type': 'application/json'
                },
                onLoggedIn: function () {
                    console.log(this.user.username + ' (' + this.userId + ') logged in');
                },
                onLoggedOut: function () {
                    console.log(this.user.username + ' (' + this.userId + ') logged out');
                },
                prettyJson: true,
                useDefaultAuth: true,
                enableCors: true
            });
    
            // Generates: POST on /api/users and GET, DELETE /api/users/:id for
            // Meteor.users collection
            Api.addCollection(Meteor.users, {
                excludedEndpoints: ['getAll', 'put'],
                routeOptions: {
                    authRequired: true
                },
                endpoints: {
                    post: {
                        authRequired: false
                    },
                    delete: {
                        roleRequired: 'admin'
                    }
                }
            });
    
            // Generates: GET, POST on /api/organizations and GET, PUT, DELETE on
            // /api/organizations/:id for the organizations collection
            Api.addCollection(Organizations, {
                excludedEndpoints: ['put', 'post', 'delete'],
                routeOptions: {
                    authRequired: true
                }
            });
    
        }
    
    });
```

Everything appears to work fine ... I run the app, then use Postman to add a user. 

All OK so far. 

Then, I go to: **http://localhost:3000/api/v1/login** and make a POST request with the body
```
{
    "password": "password",
    "email": "user@user.com"
}
```
This gives me what I expect to see:
```
{
  "status": "success",
  "data": {
    "authToken": "6Do263Poqthl7kGqrI1AnHsDir9LrrmWhdKIiyCepRs",
    "userId": "4ETkH9k4pcqGesdie"
  }
}
```
Next step is where I appear to run into trouble ... when I submit a GET request (via Postman) to **http://localhost:3000/api/v1/organizations** with the following headers:
```
Content-Type: application/json
X-Auth-Token: 6Do263Poqthl7kGqrI1AnHsDir9LrrmWhdKIiyCepRs
X-User-Id: 4ETkH9k4pcqGesdie
```
But this is what I get back:
```
{
  "status": "error",
  "message": "You must be logged in to do this."
}
```
If I set authRequired: false I get:
```
{
  "status": "success",
  "data": []
}
```
Which is what I expect to see after logging in and using the Token / UserId with **authRequired: true** in place.

I'm probably make a newb mistake but can't quite see what I'm doing wrong. 

Is there an additional header I should be using in Postman, an error in the code somewhere, or something else going on that I need to fix?

Thanks in advance for your help!

**Comment by kahmali** [comment]
Hey there! Welcome to Meteor! Hope you're enjoying it as much as I do! 😄 

Pretty easy one to fix. You overrode the default API config with some demo options that I recommend you don't use (I warned against it in the docs right above [the section that code came from](https://github.com/kahmali/meteor-restivus#coffeescript-1), but I should probably make the warning bigger and bolder to make it more conspicuous). Believe it or not, you'd get the configuration you wanted by just doing the following:

```js
var Api = new Restivus({
  version: 'v1',
  useDefaultAuth: true
});    

// ...
// setup your routes/collections
```

**That's it!** Everything else looks good there. Try that on for size and let me know how it works out.

**Comment by leanwebtools** [comment]
That did the trick, thanks!

**Comment by kahmali** [comment]
Awesome! Thanks for following up. I added a new issue (linked above) to make that warning more obvious in the docs.
