### ISSUE TITLE
How to create a catch all route? (or best practice for handling)

### ISSUE THREAD

**Issue by LaughingBubba** [kahmali/meteor-restivus#212]
It wasnt clear here #50 what the actual resolution was. 

In essence restivus works fine for the collections / routes I've defined
eg: curl "http://localhost:3000/api/v1/samples/"

But If some one hits the server with a typo
eg: curl "http://localhost:3000/api/v1/lulz/"

You get the usual meteor gumpf with a http status code of 200 (in this case this is definitely not OK) 
I particularly don't lexposing what stack I'm using to the curious. 

I have tried a custom route with regex (.) but that doesn't seem to work either.

Happy to PR and update the doco if theres something self evident but not explicitly stated (aka I missed something obvious)

Cheers

**Comment by kahmali** [comment]
Sorry, I completely missed this. There's no known solution, as I just haven't had the time to work on Restivus recently. Let's keep the discussion all in one place. We have the reference to this issue in the original, so I'm gonna close this one down.
