### ISSUE TITLE
Add the ability to change 401/403 messages.

### ISSUE THREAD

**Issue by peshi** [kahmali/meteor-restivus#214]
It would be very nice if one could change the messages for 401 and 403 messages for endpoints or have something more generic like 'Forbidden' and 'Invalid Credentials'

https://github.com/kahmali/meteor-restivus/blob/devel/lib/route.coffee#L150
https://github.com/kahmali/meteor-restivus/blob/devel/lib/route.coffee#L153

**Comment by todda00** [comment]
Agreed, It would be ideal to accept an object mapping the status code and body to the return like this:

```
const throwError = (code,msg) => {
  return {
    statusCode: code,
    body:{
      status: "error",
      message: msg
    }
  }
}
const API = new Restivus({
  apiPath: 'api/',
  version: 'v1',
  auth: {
    user(){
      console.log(this.request.headers.authorization);

      if (this.request.headers.authorization === undefined){
        return throwError(401,'Authorization header required.');
      }
      ... [rest of validation]
    }
  }
});
```
I assumed it would return my error code and message, but instead it is hard coded to "You must be logged in to do this." Which to the developer is not as helpful since I am not using standard login authorization.

**Comment by todda00** [comment]
PR to return data from auth.user() #225

**Comment by kahmali** [comment]
PR #225 has been merged, with some fixes mentioned in the PR thread. Please check there for more details, or see the update to the docs [here](https://github.com/kahmali/meteor-restivus#auth) (at the end of the section on configuring custom auth).
