### ISSUE TITLE
"undefined is not a function" BCrypt breaking bug.

### ISSUE THREAD

**Issue by AlexCatch** [kahmali/meteor-restivus#219]
When using the /login endpoint with Restivus, I get the error above when attempting to authenticate, the error originates from BCrypt. the function being called is the compare function which does the following according to the comments above it. 'compare raw data to hash'

The error is thrown on line 152 in bcrypt.js in the .meteor folder:
`/.meteor/packages/npm-bcrypt/.0.8.6_1.15txb9p++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/bcrypt.js:152`

This line throws the error:
`cb(new Error('data and hash must be strings'));`

Printing out the parameters, all of them are null but it expects there to be three params (data, hash, cb).

Below is a copy of the error thrown.
`W20160617-13:18:50.387(1)? (STDERR) /Users/alexcatchpole/.meteor/packages/npm-bcrypt/.0.8.6_1.15txb9p++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/bcrypt.js:152
W20160617-13:18:50.387(1)? (STDERR)             cb(new Error('data and hash must be strings'));
W20160617-13:18:50.387(1)? (STDERR)             ^
W20160617-13:18:50.389(1)? (STDERR) TypeError: undefined is not a function
W20160617-13:18:50.389(1)? (STDERR)     at /Users/alexcatchpole/.meteor/packages/npm-bcrypt/.0.8.6_1.15txb9p++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/bcrypt.js:152:13
W20160617-13:18:50.390(1)? (STDERR)     at process._tickCallback (node.js:458:13)`

**Comment by kahmali** [comment]
Can you please provide reproduction steps or a sample repo demonstrating the issue? What version of Restivus and Meteor are you using?

**Comment by AlexCatch** [comment]
@kahmali This was down to communication issues with the team, I assumed the account had a password tied to it but QA hadn't gone through the process to set a password before attempting to login. This issue is caused when a user who doesn't have a password attached, attempts to login.
