### ISSUE TITLE
Using Meteor as a classic Rest API with a classic node.js ORM

### ISSUE THREAD

**Issue by yanisIk** [kahmali/meteor-restivus#22]
Hi fellow developers,

First of all, thanks to kahmali for this great package, it adds a lot to Meteor but the community doesn't seem to see its potential.

Why I'm saying this ? Well, because I believe that we can **use Meteor as a normal Rest API with some other databases using node.js connectors.**

Some will say : Meteor isn't made for that ! But seriously, stop thinking that Meteor is just for hacking some little projects and never use them at scale. 

Personnaly, I have a serious project in mind, I would love to do it **the Meteor way but also the classic way and I don't want to use 2 different frameworks to build the same app !**

And this is a pretty basic scenario and I don't think that I'm the only one thinking about that. **Let's use Meteor the same way we use Express or any other Rest framework and stop using it as a toy !**

As a backend developer,  my app has to integrate with many **different clients that I DON'T CONTROL**. Some want to use a Rest API, others don't. 

Also, it would be great to see **Meteor using other databases with all the connectors that node.js have, but not in a hacky way. There are great node.js ORMs like sequelize or bookshelf that are used in many other node.js frameworks like Express. 
Why not use them with Meteor as they are used in the others ?** (yes, we need to wrap the calls, but that's not a big problem and it makes the code looks cleaner).

I think that the community doesn't seem to see the true power of Meteor, and sadly it's seen like that outside of it because most of the other developers tell me that Meteor is just a toy to prototype but they would never use it for big scalable projects like they use Express.

I'm saying this to you and your community because I think this is the first step for Meteor to be used as a Rest API.

Thank you and sorry for this long post, I know this is not an issue, but I had anywhere else to talk about that because people (Meteor community) don't care, they just tell me to use Express instead...

**Comment by kahmali** [comment]
Hey @yanisIk! I love the enthusiasm! I won't have time to give you a complete response until this weekend, but I did want to pass along one piece of information in the meantime.

You'll be happy to learn that Meteor is already being used in production, by multiple startups that have raised millions in funding. One of the core Meteor developers, [listed a bunch of them here](http://www.quora.com/Which-startups-use-Meteor-in-production). Meteor with MongoDB is production-ready. It may not be as scalable as as other, more mature, frameworks might be, but depending on your needs and your faith, Meteor and Mongo could be exactly what you need. I'm currently using it to build an application I have every intention on bringing to production, and a REST API will be exposed for it using Restivus. 

I promise I'll give you a more thorough answer this weekend.

**Comment by yanisIk** [comment]
Hi kahmali,

Can you look at this thread ? https://forums.meteor.com/t/official-rest-api-support-in-meteor/2864/5
There are some closed mind people thinking that Meteor is only for DDP....

**Comment by kahmali** [comment]
Looks like you could be getting your wish sooner than expected. I just saw this package's release being tweeted out by one of the core Meteor devs, Slava Kim:

https://github.com/numtel/meteor-pg

Check it out and be sure to keep an eye on it. It appears to support reactive PostgreSQL in Meteor.

**Comment by yanisIk** [comment]
Thanks I saw it too. But I think I will just wait for Meteor to be more mature and support more things. It isn't going the way I thought, they are focusing too much on front end and ''fullstack'' stuff. I'm only interested in Meteor as a backend, and Meteor's backend is really limited right now and the community doesn't care, they just want to focus on front end stuff to make hello world apps easier...

I'll go the node.js way, probably with pure Express + SocketIO (to learn node basics) and use RethinkDB 2.0 to stream the changes the Meteor way (but way more performant).
I'll let the front end to the front end guys, so they can work with wathever framework they want.

I hope that when I'll come back, Meteor will be more modular, open, and usable as a pure backend and that your package will become the Iron-Router of Rest API haha.


Do you want me to close this ? ( Since it is not an issue but just a ''debate'' )
