### ISSUE TITLE
Pass authentication token and user ID as URL parameters

### ISSUE THREAD

**Issue by pvmeijel** [kahmali/meteor-restivus#220]
I would like to be able to pass the authentication token and user id as URL parameters, rather than as headers.

**Comment by kahmali** [comment]
You need to write what I've poorly named a "[partial auth function](https://github.com/kahmali/meteor-restivus#auth)" that parses the URL parameters and add it to your [API configuration](https://github.com/kahmali/meteor-restivus#configuration-options). It'll look something like:

```js
var Api.V1 = new Restivus({
  useDefaultAuth: true,
  version: 'v1'
  auth: {
    user: function () {
      return {
        userId: this.urlParams.userId,
        token: this.urlParams.token
      };
    }
  }
});
```

Restivus will then validate the `userId` and `token` you return (using the default auth). I'm going to close this issue, but feel free to continue the discussion or reopen it if you have any difficulty getting this to work. Thanks for the question!
