### ISSUE TITLE
Can't login via CURL

### ISSUE THREAD

**Issue by skemb321** [kahmali/meteor-restivus#245]
Hi, please help I tried logging in to the api via curl. Already created a user using Accounts package and verified that i can login via browser (Meteor.loginWithpassword).

Request:
```
curl http://localhost:3000/api/v1/login -d "username=myuser&password=mypassword"
```
Response:
`
{
  "status": "error",
  "message": "Unauthorized"
}
`

Meteor version:
1.4.2

**Comment by skemb321** [comment]
CURL having problems sending passwords (strong) with special characters :( As an alternative, you can just use a hashed alphanumeric passwords.

**Comment by kahmali** [comment]
I think you just need to URL encode those special characters. cURL has a [command](http://stackoverflow.com/a/10279363/2280663) for doing that actually.

**Comment by skemb321** [comment]
@kahmali thanks will try that!
