### ISSUE TITLE
Expire token

### ISSUE THREAD

**Issue by jykae** [kahmali/meteor-restivus#252]
Could we add "when" property for generated token, so it would expire based on "loginExpirationInDays" value set for Accounts config?

https://github.com/kahmali/meteor-restivus/blob/66f1348fec264d6e96860fb2b7b1298c1c3784b3/lib/auth.coffee#L59

Accounts config:
http://docs.meteor.com/api/accounts-multi.html#AccountsCommon-config

**Comment by jykae** [comment]
ping @kahmali

**Comment by jykae** [comment]
Closing as binding to login expiration might be bad idea.

**Comment by chriscarpenter12** [comment]
@jykae I agree there needs to be some kind of expiration on the tokens generated. Not necessarily "loginExpirationInDays", but some arbitrary value we can set for the token lifetime. If someone is programmatically hitting our api, and they "login" each time at the start of their call or script it can potentially generate hundreds or thousands + of tokens... With some auto expire timeframe we can alleviate this issue.
