### ISSUE TITLE
Asynchronous database calls

### ISSUE THREAD

**Issue by rufffneck** [kahmali/meteor-restivus#254]
Hi, is there a way I could make my queries async. Like when doing a lot of update operations and i wish for them to be non-blocking so I could better my API's response time.

**Comment by kahmali** [comment]
Please see the discussion [here](https://github.com/kahmali/meteor-restivus/issues/11) for my answer on asynchronous REST endpoints.

**Comment by rufffneck** [comment]
Yes I had seen that, but It doesnt seem right that we dont have the option of writing asnc db queries, which is default node behaviour. From what I understand meteor itself wraps all queries in something like async wrap and which is what restivus is built upon. But shouldnt a way exist by which we can undo the synchronous behaviour given by meteor.

**Comment by rufffneck** [comment]
ping kahmali
