### ISSUE TITLE
Using restivus with Meteor.call

### ISSUE THREAD

**Issue by digitaldeus** [kahmali/meteor-restivus#260]
Hi,

Could anyone provide an example of how to use restivus with a Meteor.call function?  I can't seem to get it working and I have tried with the fibers/future package:

```
Api.addRoute('search', {authRequired: false}, {
  get: function () {
    // TODO: validate API Call

    const {
      term,
      location,
      limit,
      offset
    } = this.queryParams;
    
    console.log(Npm);
    console.log(Future);
    const fut = new Future();

    Meteor.call('searchChurch', {
      term,
      location,
      limit,
      offset
    }, (err, res) => {
      if (err) {
        fut["return"]({
          error: err
        });
      } else {
        fut["return"](res);
      }
    });

    return fut.wait();
  }
});
```

Really appreciate your help!

**Comment by lucasprag** [comment]
@deusd I think could do something like this:

```javascript
Api.addRoute('search', {authRequired: false}, {
  get: function () {
    // TODO: validate API Call

    const {
      term,
      location,
      limit,
      offset
    } = this.queryParams;

    Meteor.call('searchChurch', { term, location, limit, offset }, (err, res) => {
      if (err) {
          this.response.writeHead(err.error);
          this.response.write(JSON.stringify(err));
      } else {
          this.response.writeHead(200);
          this.response.write(JSON.stringify(res));
      }
      this.done();
    });
  }
});
```

As you can see, you can write things on response and the result only will be returned when `this.done()` is called.

I hope to have helped.

**Comment by kahmali** [comment]
It's actually even simpler than that @Lucasosf. When you use Meteor.call on the server, simply don't pass a callback and the method will return the value or an error synchronously. Easy peasy, lemon squeezy. From the [docs](http://docs.meteor.com/api/methods.html#Meteor-call):

>If you do not pass a callback on the server, the method invocation will block until the method is complete. It will eventually return the return value of the method, or it will throw an exception if the method threw an exception.

**Comment by lucasprag** [comment]
@kahmali nice! I didn't know that.

A new day, a new lesson, thanks =)

**Comment by digitaldeus** [comment]
Wow awesome thanks guys!
