### ISSUE TITLE
restivus breaks iron:router on deployed apps

### ISSUE THREAD

**Issue by hujhax** [kahmali/meteor-restivus#3]
Check out the following two deployed apps:
[functional site](http://peter-testivus-works.meteor.com/)
[busted site](http://peter-testivus-broken.meteor.com/)

They are both supposed to show a homepage, but the second one shows the iron:router splash page.  The only difference between them is that [I initialized a RESTivus endpoint in the latter one](https://github.com/hujhax/testivus/commit/defa19fd8cae42b8cf23ca9b3bdb9cc755b1b208).

The busted site still works fine on my local server -- it only gets confused and splash-screen-y when I deploy it.  I've tried deploying to meteor and to heroku -- both produce the same result.

**Comment by kahmali** [comment]
Alright, let me look into this. I have the latest version of Restivus in an app that uses Iron Router fairly extensively, and it's deployed on both meteor and digital ocean and both are working fine. There must be something else to the error besides simply having Restivus in the deployed app. I absolutely hate those Iron Router errors. I get them all the time and the strangest things seem to cause them. So frustrating! I'll check out your repro apps and keep you posted. Thanks for reporting the issue.

**Comment by hujhax** [comment]
Thanks!  And let me know if there's anything I can do to help.

**Comment by kahmali** [comment]
I think you made your test repo private. Could you please add me as a collaborator or make it public so I can check it out?

**Comment by hujhax** [comment]
Derp!  I am not smarting well today.  It's public now.

**Comment by kahmali** [comment]
I was able to get it to run when [deployed on meteor](http://testivus-kahmali.meteor.com/) by making the call to `Restivus.add()` from within `Meteor.startup()`. So in lib/restivus.js:
Change:
```javascript
Restivus.add('test', {
    get: {
        action: function() {
            return "Hello World!";
        }
    }
});
```
to this: 
```javascript
Meteor.startup(function () {
    Restivus.add('test', {
        get: {
            action: function() {
                return "Hello World!";
            }
        }
    });
});
```

Would you be able to test that on Heroku when you have a chance and let me know if it works? I will make sure I add that to the docs. I've always done it that way, but I need to say it explicitly in the docs. Sorry about that!

**Comment by hujhax** [comment]
We're good on heroku!  Thanks so much!

**Comment by kahmali** [comment]
Alright, I updated the docs with that information. Sorry if you were alerted each time I rebased that commit. I have to push to test the GitHub markdown, and I was just making some minor cosmetic updates so I had to squash the commits.
