### ISSUE TITLE
this.userId is empty in authenticated API endpoints

### ISSUE THREAD

**Issue by hujhax** [kahmali/meteor-restivus#4]
When we have a call that requires authentication, we can still authenticate properly, but this.userId is blank when we reach that code.

This worked in 0.5.3, but was broken in 0.5.4.

Check out [this branch](https://github.com/hujhax/testivus/tree/bugs/blank-userID), which shows an example of the behavior.

**Comment by kahmali** [comment]
I just published [v0.5.7](https://github.com/kahmali/meteor-restivus/compare/v0.5.6...v0.5.7) that should fix the issue (and probably create ten more at the rate I'm going). Check out the [commit](https://github.com/kahmali/meteor-restivus/commit/6fb30903) or the change log for more details. If you need a more detailed explanation than what's there just let me know. My plan is to implement some automated testing next weekend to avoid these sneaky bugs when updating in the future. Thanks so much for reporting another issue! I'll try my best to make this a less frequent occurrence for you.

**Comment by hujhax** [comment]
w00t!  Looks like it works fine!

Velocity looks really good, and this package seems conducive to unit tests, so I'm sure you'll get a good test suite together.  Good luck!
