### ISSUE TITLE
Error: Meteor.userId can only be invoked in method calls.

### ISSUE THREAD

**Issue by vhuerta** [kahmali/meteor-restivus#40]
Hi, Im getting this error:

Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions. at Object.Meteor.userId

Im just create this file (/server/services/rest_services.js): 

```javascript
    Restivus.configure({
        apiPath: 'api/',
        useAuth: true,
        prettyJson: true,
        enableCors: true
    });

    Restivus.addRoute('user/email_change/:email', {authRequired: false}, {
        get: function () {

        }
    });
```

Why do you think this happens ?

**Comment by vhuerta** [comment]
ok i found why this was happening, because i have this in my router configuration: 

```javascript
Router.onBeforeAction(function () {
    if (!Meteor.userId()) {
        this.redirect('/login');
    }
    this.next();
});
```

i changed to 

```javascript
Router.onBeforeAction(function () {
    if (!Meteor.isServer && !Meteor.userId()) {
        this.redirect('/login');
    }
    this.next();
});
```

and now is working fine

**Comment by kahmali** [comment]
Thanks for reporting this issue and updating it with the solution! Unfortunately, I don't think #38 will fix this. I'll have to test to see if iron router hooks run before routes that aren't defined with iron router.
