### ISSUE TITLE
Allow default endpoints to be configured in API for each HTTP method

### ISSUE THREAD

**Issue by kahmali** [kahmali/meteor-restivus#51]
```coffeescript
config:
  defaultEndpoints:
    post: ->
    get: -> 
    put: ->
    patch: ->
    delete: ->
    options: ->
```

**Comment by kahmali** [comment]
Ultimately, I decided to only allow a default OPTIONS endpoint to be configured, for now at least. If someone makes a compelling argument for any of the others, I'll certainly reconsider. I just couldn't think of a use case for any of the others. Merged to the `0.7.0` branch.

**Comment by winniehell** [comment]
If the same meteor instance serves a client app and a REST API, missing endpoints (e.g. typos) may lead to HTTP status 200 because they are handled by the client app. Default endpoints could prevent that and return 404 instead.

**Comment by kahmali** [comment]
Sorry for the offensively delayed response on this! I've been caught up on some other work and this slipped through the cracks. 

The plan is to implement that behavior via a catchall API route (#50). I would gladly accept a PR for it! :D

**Comment by winniehell** [comment]
Sounds reasonable, thanks!
