### ISSUE TITLE
Add default OPTIONS endpoint

### ISSUE THREAD

**Issue by kahmali** [kahmali/meteor-restivus#52]
Use #51 and provide an API config option (something like `useDefaultOptionsEndpoint`)

**Comment by kahmali** [comment]
Hey @gabrielpoca! I'm _finally_ getting around to implementing a default OPTIONS endpoint and I was wondering if you had any example code you could share from any OPTIONS endpoints you created? Did you always find yourself setting up a single OPTIONS endpoint that every route shared, or did you have special needs in your OPTIONS for certain routes or endpoints? Just trying to see what I should be creating as a default and what I can add configuration options for, to avoid forcing users to completely override the default endpoint. You worked on #9, so I thought you might have some insight on this. Your input would definitely be appreciated here!

**Comment by gabrielpoca** [comment]
@kahmali I don't have much experience with the OPTIONS method. I don't have anything on Github on this, but responding with 200 and the right headers is enough, if I remember correctly. The OPTIONS request can also be used to ping a server, when used with an asterisk as the request uri.

**Comment by kahmali** [comment]
Thanks so much for responding @gabrielpoca! That sounds consistent with other resources I've come across. One cool suggestion I saw was using the OPTIONS method to provide some basic documentation for REST endpoints. My goal is to eventually support autogenerated API docs, and I'll definitely look into adding that as a configuration option on the API, as well. Thanks for your input!

**Comment by gabrielpoca** [comment]
@kahmali :+1: nice. Btw, awesome package. It's on my list to contribute whenever I find the time.

**Comment by kahmali** [comment]
Thanks!! Your contributions are always appreciated!

**Comment by MartiniHenry1988** [comment]
I am still getting issue with CORS in case of 401 status from api.
In case of success 200 it works fine,

Here is my config:

```
myApi = new Restivus({

    apiPath: 'api/',
    defaultHeaders: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Credentials": "true",
      "Access-Control-Allow-Headers": "Access-Control-Allow-Headers, Access-Control-Request-Method, Connection, Content-Language, Access-Control-Request-Headers, Origin, X-Requested-With, Content-Type, Accept-Language, Accept, Z-Key, Authorization, client-id, client-secret, client_id, client_secret",
      "Content-Type": "application/json",
      "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS"
    },
    enableCors: true,
    useDefaultAuth: false,
    prettyJson: true,
    defaultOptionsEndpoint: {
        action: function() {
            this.response.writeHead(201, {
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Credentials": "true",
                "Access-Control-Allow-Headers": "Access-Control-Allow-Headers, Access-Control-Request-Method, Connection, Content-Language, Access-Control-Request-Headers, Origin, X-Requested-With, Content-Type, Accept-Language, Accept, Z-Key, Authorization, client-id, client-secret, client_id, client_secret",
                "Content-Type": "application/json",
                "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS"
            });
            this.done();
            return {
                status: "success",
                "data": {
                    "message": "We love OPTIONS"
                }
            };
        }
    }
});
```
