### ISSUE TITLE
returning XML?

### ISSUE THREAD

**Issue by wesyah234** [kahmali/meteor-restivus#61]
Is it possible to return XML if a client needed it? rather than json?  Thanks.

**Comment by kahmali** [comment]
Yes, it is possible. All you need to do is set a non-JSON `Content-Type` header in your response. In your case it should be `application/xml`. You can do this on an individual endpoint, or you can override the default content type, which is `application/json`.

To [set the content type in an endpoint](https://github.com/kahmali/meteor-restivus#response-data):
```coffeescript
Restivus.addRoute 'send-xml', 
  get: ->
    headers: 
      'Content-Type': 'application/xml',
      'X-Custom-Header': 'custom value'
    body: someXmlBody
```

And to [override the default header](https://github.com/kahmali/meteor-restivus#configuration-options):
```coffeescript
Restivus.configure
  defaultHeaders: 
    'Content-Type': 'application/xml'
```

Let me know if this doesn't work for you for some reason.

**Comment by wesyah234** [comment]
I'm doing this:
        return {
          statusCode: 404,
          headers: {
            'Content-Type': 'text/plain',
            'X-Custom-Header': 'custom value'
          },
          body: {
            status: 'success',
            data: {
              message: 'There is nothing here!'
            }
          }
        };
and it errors with:
TypeError: first argument must be a string or Buffer
 at ServerResponse.OutgoingMessage.write (http.js:852:11)

**Comment by kahmali** [comment]
What version are you using? A bug that prevented this from working was fixed in v0.6.5. I have tests for this that are passing in the latest versions.

**Comment by wesyah234** [comment]
meteor list
meteor-platform  1.2.2  Include a standard set of Meteor packages in your app
nimble:restivus  0.6.5  Create authenticated REST APIs in Meteor 0.9+. Setup CRUD endpoints for Collections.

**Comment by kahmali** [comment]
Oh, sorry. You're still passing JSON even after saying that the content type wont be JSON. You need to just return a string there.

**Comment by wesyah234** [comment]
but I'm using the example here:
https://github.com/kahmali/meteor-restivus#response-data
it seems that you need to return json to indicate the content type, then it seems the message element of the body element is where you return the actual data ?? confused.

**Comment by kahmali** [comment]
Do as I say, not as I do. :) That's just an error. Thanks for catching that! I fixed the bug but missed that in the sample code.

**Comment by kahmali** [comment]
Oh, I see what you're saying now. I tried to explain, in that section of the docs, that you can either return a raw string (you would need to have already set the default content type to non-JSON), a raw js object, or if you want to override the default headers or the status code, you can return an object with `headers`, `statusCode`, and `body`, where body should contain the raw response. 

If you think that it's not clear, please file an issue for it and I'll fix it. I'll definitely fix the issue I was referring to, which was that I have the content type set to `text/plain` and I return a js object in the example. Sorry for any confusion there.

**Comment by wesyah234** [comment]
ok, so an xml example would be like this:

        return {
          statusCode: 200,
          headers: {
            'Content-Type': 'application/xml',
            'X-Custom-Header': 'custom value'
          },
          body: "<body><message>my message</message></body>"
        };

got it now, thanks!

**Comment by kahmali** [comment]
Exactly! And no, thank _you_ for reporting the documentation errors. Much appreciated!

**Comment by wesyah234** [comment]
no prob. do you know of a meteor library to convert json to xml?  that would be useful for my example use case where I want to return xml, but I'm storing data as json.
