### ISSUE TITLE
Pass authenticated user to meteor method

### ISSUE THREAD

**Issue by outaTiME** [kahmali/meteor-restivus#69]
Hi guys, how pass userId to Meteor method this is my scenario:

```js

Restivus.addRoute('devices/:id', {authRequired: true}, {
  delete: {
    action: function () {
      var deviceId = this.urlParams.id;
      return Meteor.call('deleteDevice', deviceId);
    }
  }
});

Meteor.methods({
  deleteDevice: function (deviceId) {
    if (!this.userId) {
      throw new Meteor.Error('not-authenticated', 'User must be logged in to perform this operation')
    }
    check(deviceId, String);
    // pass
  }
});

```

the userId never exist in Meteor method context, how can resolve that without passing userId as method param.

thks !

**Comment by outaTiME** [comment]
Note, `deleteDevice` method is shared we use from restivus and meteor app ...

thks !

**Comment by kahmali** [comment]
Check out [`simple:rest`](https://atmospherejs.com/simple/rest) for automatically exposing HTTP endpoints for your `Meteor.methods`. I believe it uses standard bearer token auth to provide access to `this.userId` from the autogenerated HTTP endpoints.

You're correct that the only way to currently do this with Restivus is to pass the `userId` as a parameter to the Meteor method.

**Comment by outaTiME** [comment]
Oups, but i need a custom API definition i dont want to expose my meteor methods.

Its not possible to inject the restivus userId into meteor method context ?? with the setUserId:

http://docs.meteor.com/#/full/method_setUserId

**Comment by kahmali** [comment]
`this.setUserId` is only available within the context of the `Meteor.method`. Restivus does not currently interact with Meteor methods in any way. Based on the implementation in `simple:rest` (which was built by a dev from MDG), it looks like there is no trivial solution for setting the context of a `Meteor.method` (or just setting the `userId` for that matter). It's also not within the scope of Restivus at the moment, but that's always open to debate. Maybe you could create an issue or pull request on `simple:rest` to only expose certain Meteor methods over HTTP? Or maybe @stubailo (the creator of `simple:rest`) wouldn't mind chiming in right here on what appears to be a bit of a gap between `simple:rest` and Restivus? He may have some insight on the best place to implement such functionality.

**Comment by outaTiME** [comment]
Woow heavyweight ... by the moment i update my meteor method to support the userId as paramater:

```js
Meteor.methods({
  deleteDevice: function (deviceId, userId) {
    userId = userId || this.userId; // for restivus
    if (!userId) {
      throw new Meteor.Error('not-authenticated', 'User must be logged in to perform this operation')
    }
    check(deviceId, String);
    // pass
  }
});
```

not the better way but is functional, very high risk to expose this method 'cos if we know an userId and device may i delete this document without any authentication mechanism ...

**Comment by kahmali** [comment]
Yeah, not very secure at all. Something a little more ugly but a lot more secure might be extracting the function to somewhere only accessible on the server, then using that same function as both the meteor method, and then manually calling it from your Restivus route. That way you can trust Meteor's auth in the method and Restivus' auth in the route. Something like:

```js

Restivus.addRoute('devices/:id', {authRequired: true}, {
  delete: {
    action: function () {
      var deviceId = this.urlParams.id;
      return deleteDevice.call({userId: this.userId}, deviceId);
    }
  }
});

Meteor.methods({
  'deleteDevice': deleteDevice
});

var deleteDevice = function (deviceId) {
    if (!this.userId) {
      throw new Meteor.Error('not-authenticated', 'User must be logged in to perform this operation')
    }
    check(deviceId, String);
    // pass
  }
```

**Comment by outaTiME** [comment]
Yup, pal ... you are right more secure in that way ... i will create a common file in server side an put shared methods there ...

thks for your time :+1:

**Comment by kahmali** [comment]
No problem! I made a minor edit in the code example. I'm glad it's an acceptable solution (even if it's not the cleanest). Thanks for taking the time to file the issue and follow up!

**Comment by outaTiME** [comment]
Great, thks once ...

**Comment by stubailo** [comment]
Going to look into this, thanks for the heads up @kahmali

**Comment by outaTiME** [comment]
Great to hear that @stubailo !!! @kahmali, i update you code adding the unblock method in the meteor method but not in the restivus take a look, what do you think ?? here the complete example:

```js
Restivus.addRoute('devices/:id', {authRequired: true}, {
  delete: {
    action: function () {
      var deviceId = this.urlParams.id;
      var userId = this.userId;
      return deleteDevice.call({userId: userId}, deviceId);
    }
  }
});

Meteor.methods({
  deleteDevice: function (deviceId) {
    // let other method calls from the same client start running, without waiting for the complete.
    this.unblock();
    // common call
    return deleteDevice.call(this, deviceId);
  },
});

var deleteDevice = function (deviceId) {
  var userId = this.userId;
  if (!userId) {
    throw new Meteor.Error('not-authenticated', 'User must be logged in to perform this operation')
  }
  check(deviceId, String);
  // TODO: extract generic method to common.js
  var user = Meteor.users.findOne({
    _id: userId,
    devices: {$in: [deviceId]}
  });
  if (!user) {
    throw new Meteor.Error('device-not-found', 'Cannot find the specified device');
  }
  Devices.update(deviceId, {
    $set: {
      deletedAt: new Date(),
    }
  });
  return deviceId;
}
```
regards !!!

**Comment by kahmali** [comment]
Thanks so much for looking into this @stubailo! And for being so responsive, as always!

@outaTiME That looks great to me, assuming you're okay with any side effects of unblocking in that method. As long as you've made that consideration, the code looks solid. I'll leave this issue open for now, until Sashko has some time to look into it. Thanks for reporting the issue!

**Comment by outaTiME** [comment]
@kahmali findOne / update operation are not really blocking the subsequents calls but i only leave "unblock" call for skeleton purpose (reuse in the future in a more complex method)

**Comment by kahmali** [comment]
After giving this some more thought, I don't really see any reason to manage your DDP and REST API separately. I will continue to support Restivus until we can get all the existing functionality carried over to `simple:rest` and it's add-on packages, but the goal is to eventually have that as the de facto REST solution for Meteor. I explained in a little more detail here: https://github.com/stubailo/meteor-rest/issues/23#issuecomment-104441219. I still believe that Restivus is currently the best way to create a REST API in Meteor (especially with the 0.7.0 updates), but hopefully we'll change that soon, for the better.

**Comment by adamgins** [comment]
@kahmali Thanks for restivus

Just wondering, as this is a relatively old post... if I want to have an authenticated rest API that then calls a Meteor method (that's actually a microService).. any update on which way I should go. 

I can authenticate with a restivus call.. but when I call a Meteor method, it shows that `userId` is `null`

**Comment by kahmali** [comment]
Thanks @adamgins! 

Well, it's not ideal, but I would recommend you just extract your existing Meteor method into a method accessible to your Meteor methods _and_ REST API, and then call that method from both the Meteor method and within the authenticated endpoint. It's not the DRYest solution, but it works. I gave a code example in [this comment above](https://github.com/kahmali/meteor-restivus/issues/69#issuecomment-101938982).

That's currently the best solution I can think of, as I'm still not comfortable modifying the Meteor methods to inject the `userId` in there. Sorry. I hope that's an acceptable solution for you.

**Comment by adamgins** [comment]
@kahmali Thanks for the quick response.

**Comment by kahmali** [comment]
No problem!

**Comment by stubailo** [comment]
@adamgins if you use ValidatedMethod, you can call the method body from the server with whatever userId you like using `_execute`: https://atmospherejs.com/mdg/validated-method

**Comment by kahmali** [comment]
Awesome! Thanks Sashko!

**Comment by adamgins** [comment]
@stubailo thanks!!!

**Comment by adamgins** [comment]
@stubailo thank again for the response. Ok, so I got simple version of `ValidatedMethod` working with `_execute` and passing the `userId`. I am planning to call a method in a microservice as per https://forums.meteor.com/t/rest-api-how-do-i-ddp-connect-as-a-specific-user-on-the-server/15783

So I'd do something like,
 ```
var logConn = DDP.connect("http://localhost:3000");
 logConn.call("someRemoteMethod", someParamToPass, function(err, result){
                if (err){
                    console.log("Err", err)
                } else {
                    console.log("Res:", result)
                }
            })
```

So I am thinking that, this will not work.. ie it will not make an authenticated call to `someRemoteMethod` or is there some way I can do a DDP call to `someRemoteMethod` from one Meteor app to another?

**Comment by stubailo** [comment]
Oh, I thought you were talking about something else. If you want to call a method across servers impersonating a user, you'll need to do something else.

First, you should definitely make sure that the connection is secure and that it's the real server - this is super important if you're going to bypass the login system.

Then, you would want to pass the userId as an argument.

I hope a future version of the accounts system has an easier way to be logged in to multiple services at once.
