### ISSUE TITLE
Iron-Router Error: request entity too large at makeError

### ISSUE THREAD

**Issue by michaelleuzinger** [kahmali/meteor-restivus#78]
Hi,

I'm trying to upload json data to my application via a POST request to the Restivus REST API. The json data has about 350kByte of size.

Unfortunately I receive this error message: "Error: request entity too large at makeError"
I suppose I found the solution here: https://github.com/iron-meteor/iron-router/issues/710

How can I achieve this in Restivus? Is there a way to configure the routers centrally like the Restivus.configure() stuff?

**Comment by kahmali** [comment]
Let me check if this is specific to Iron Router (the Iron Router dependency has been removed from Restivus in the unreleased v0.7.0). From the issue you referenced, it appears it may be a property that can be set on the Connect `bodyParser` middleware (this middleware is used in the Iron Router replacement, JsonRoutes, as well). I'll look into providing an option in Restivus for increasing the size limit. I probably won't have a chance to look into this until later tonight. I'll keep you posted. Sorry for the inconvenience!

**Comment by joetm** [comment]
I am having the same issue.

**Comment by kahmali** [comment]
This could be a fairly simple fix if it's just a matter of setting a config option in the `bodyParser`. I'll look into this tonight and get back to you. I'm going to do this on the 0.7.0 branch, because I just can't deal with Iron Router and all the headache that comes along with that anymore. I will make a strong effort to do the 0.7.0 release this weekend, or no later than next week. It's all the doc updates that are taking the longest.

**Comment by kahmali** [comment]
Would either of you be able to share a sample request body with me for testing?

**Comment by michaelleuzinger** [comment]
I'll try to do so tomorrow morning (GMT+1) - so in about 14 hours.

Kahmali Rose <notifications@github.com> schrieb am Mo., 15. Juni 2015 um
20:13 Uhr:

**Comment by kahmali** [comment]
Awesome. Thanks @michaelleuzinger!

**Comment by michaelleuzinger** [comment]
Late but hopefully not too late...
https://github.com/michaelleuzinger/files/blob/master/large.json

**Comment by samybob1** [comment]
You have to configure the bodyParser on the server side in order to allow bigger requests :

```
Router.configureBodyParsers = function() {
    Router.onBeforeAction(Iron.Router.bodyParser.urlencoded({
        extended: true,
        limit: '20mb'
    }), {where: 'server'});
};

```

**Comment by kahmali** [comment]
Thanks for the test data @michaelleuzinger! And thanks for the information @samybob1! I _would_ add an API config option to get rid of the boilerplate, but I'm close to releasing v0.8.0, which removes Iron Router, so we'll need to add a means of increasing the body size limit in simple:json-routes (the iron router replacement), and I'll provide a config option whenever that's taken care of. Sorry for being so slow on a resolution for this.

**Comment by heiligeslama** [comment]
Hi, I have the same problem with json-routes and large POST requests. Is there a way to deal with that?
Thanks for you time.

**Comment by kahmali** [comment]
Hi @heiligeslama. Thanks for reporting this issue. I knew it was coming, as you can see from my comment above :) I filed an [issue](https://github.com/stubailo/meteor-rest/issues/75) on the `simple:json-routes` repo with  a suggested fix. If you have the time and means you could always submit a PR for it to get the ball rolling a lot faster. Unfortunately, as I mentioned in the issue over there, I just don't have any free time to devote to this right now.

**Comment by kahmali** [comment]
The request size limit has been increased to 50mb in v0.8.6
