### ISSUE TITLE
0.7.0 ETA

### ISSUE THREAD

**Issue by azfx** [kahmali/meteor-restivus#85]
I am looking forward to the "hashedTokens" implementation, any idea when 0.7.0 will be out ?

Thanks!
Abdul

**Comment by kahmali** [comment]
v0.7.0 should be released within the next 24 hours. I'll keep you posted.

**Comment by kahmali** [comment]
v0.7.0 has just been published. Please let me know if you run into any issues with it. Thanks!

**Comment by azfx** [comment]
@kahmali , upgraded and tested, and no issues so far. Thanks!
