### ISSUE TITLE
README.md, a little mistake 

### ISSUE THREAD

**Issue by backsapce** [kahmali/meteor-restivus#93]
raw file line 919
maybe author take a little mistake
i guess it is
```js
  get: {
    authRequired: false,
    action: function () {
      // GET api/posts
    }
  },
```

**Comment by kahmali** [comment]
Good catch. Those pesky little commas! I'll fix this in the next update. Thanks for reporting it!

**Comment by kahmali** [comment]
This has been updated on the 0.8.0 branch. Thanks again for reporting this!

**Comment by backsapce** [comment]
:)
