### ISSUE TITLE
On 401, 403, the route should wait before sending any data

### ISSUE THREAD

**Issue by jazeee** [kahmali/meteor-restivus#95]
This is a small correction to #81 
Command to test:

    curl -X POST --data "user=abc&password=123" http://localhost:3000/api/login

It responds instantly with status error, etc, but then waits a random time to complete the request.

Instead, it should wait before sending *all* of the response, including the JSON and status.

I'll publish a PR for this as a simple fix.

**Comment by kahmali** [comment]
Ah. Good catch. Should be a very simple fix.
